[language-server.tinymist]
command = "tinymist"

[language-server.tinymist.config]
exportPdf = "onType"
outputPath = "./$name"

[language-server.tinymist.preview.background]
enabled = true
args = ["--data-plane-host=127.0.0.1:23635", "--invert-colors=never", "--open"]
